### ISSUE TITLE
Update vcluster Cluster API Provider Dependencies & Create new release

### ISSUE THREAD

**Issue by empath-nirvana** [loft-sh/cluster-api-provider-vcluster#32] opened 2023-06-20 18:36 UTC
What to update when updating to new vcluster / dependencies:

1. Update vcluster version in constants: [https://github.com/loft-sh/cluster-api-provider-vcluster/blob/main/pkg/constants/constants.go#L7](https://github.com/loft-sh/cluster-api-provider-vcluster/blob/main/pkg/constants/constants.go#L7)
2. Update utils: [https://github.com/loft-sh/cluster-api-provider-vcluster/blob/main/go.mod#L6](https://github.com/loft-sh/cluster-api-provider-vcluster/blob/main/go.mod#L6)
3. Update k8s dependencies in go.mod

How to create a new release:

1. Just create new release through Github Release page
2. First prerelease then update to stable release

**Comment by matskiv** [comment] 2023-06-21 09:24
Hello,
we have a task for updating deps and creating a new release in this sprint. It should happen end of this week or the beginning of the next one.

**Comment by matskiv** [comment] 2023-06-22 07:37
Just FYI, the bot closed this because it was marked as a duplicate of an internal issue about making a new release. It will be done, no need to worry :)

**Comment by empath-nirvana** [comment] 2023-06-30 16:05
is this still going to happen this week?

**Comment by rohantmp** [comment] 2023-07-04 07:01
I will be working on this very soon, but cannot say for sure if it will be done this week :)

**Comment by narcis96** [comment] 2024-04-10 08:01
discussion moved to https://github.com/loft-sh/cluster-api-provider-vcluster/issues/60

**Closed by narcis96** 2024-04-10 08:01 UTC
